### ISSUE TITLE
COCOA-cls dataset annotations

### ISSUE THREAD

**Issue by mingheyuemankong** [UARK-AICV/AISFormer#3]
Hi, according to the link given by the author, the number of images in the training set in the COCOA-cls annotation I obtained is 2276, not 2476 as described in your paper? Which one is accurate? I am looking forward to get a reply from the author.

**Comment by trqminh** [comment]
Hi, thank you for your interest in our work.
you're right, it should be 2276 as in the download link we provided in the readme.
actually, we follow this work (arxiv.org/pdf/2012.05598.pdf) to describe our dataset, and this work (https://github.com/YihongSun/Bayesian-Amodal) to download the dataset. and since the different is small, I did not recognize.

you could confirm with the author of the dataset (patrick.follmann@mvtec.com).
